CREATE OR REPLACE FUNCTION rebox_guard_ledger() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_TABLE_NAME = 'ledger_transactions' THEN
    IF OLD.status = 'POSTED' THEN RAISE EXCEPTION 'POSTED_LEDGER_IMMUTABLE'; END IF;
  ELSE
    IF EXISTS (SELECT 1 FROM ledger_transactions WHERE id = OLD.transaction_id AND status = 'POSTED') THEN
      RAISE EXCEPTION 'POSTED_LEDGER_IMMUTABLE';
    END IF;
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END $$;
