export const errorCodes = [
  "INVALID_ACCESS_TOKEN",
  "RESOURCE_NOT_FOUND",
  "EMAIL_NOT_VERIFIED",
  "SHOP_NAME_TAKEN",
  "SHOP_NOT_VERIFIED",
  "SHOP_NOT_ACTIVE",
  "FORBIDDEN",
  "REVIEW_NOT_ELIGIBLE",
  "MFA_REQUIRED",
  "IDEMPOTENCY_CONFLICT",
  "INVALID_LISTING_STATE",
  "INVALID_CATEGORY",
  "LISTING_CATEGORY_BANNED",
  "LISTING_DISCLOSURE_REQUIRED",
  "CATALOG_IMAGE_LIMIT",
  "SELLER_DOCUMENT_UPLOAD_FAILED",
  "INVALID_KYC_STATE",
  "KYC_PROVIDER_UNAVAILABLE",
  "LISTING_IMAGE_REQUIRED",
  "PII_COLUMN_FORBIDDEN",
  "SPREADSHEET_FORMAT_INVALID",
  "MANIFEST_PACKAGE_CONFLICT",
  "MANIFEST_IDEMPOTENCY_CONFLICT",
  "MANIFEST_PREVIEW_NOT_COMMITTABLE",
  "SOURCE_MANIFEST_NOT_FOUND",
  "PACKAGE_STATE_CONFLICT",
  "ONE_PACKAGE_PER_CHECKOUT",
  "MULTI_SELLER_CHECKOUT_NOT_SUPPORTED",
  "ITEM_BEING_PURCHASED",
  "ITEM_SOLD",
  "SHOP_UNAVAILABLE",
  "ADDRESS_NOT_FOUND",
  "INSUFFICIENT_SHOP_FUNDS",
  "PAYMENT_METHOD_DISABLED",
  "INVALID_ORDER_STATE",
  "INVALID_FULFILLMENT_TRANSITION",
  "EVENT_ID_CONFLICT",
  "PROCESSING_RECORD_REQUIRED",
  "DISPUTE_NOT_ELIGIBLE",
  "REFUND_AMOUNT_EXCEEDED",
  "LEGAL_ARTIFACT_NOT_FOUND",
  "STEP_UP_REQUIRED",
  "RATE_LIMITED",
  "VALIDATION_FAILED",
  "INVALID_CREDENTIALS",
  "INTERNAL_ERROR"
] as const;

export type ErrorCode = (typeof errorCodes)[number];

export type ErrorResponse = {
  error: {
    code: ErrorCode;
    message: string;
    requestId: string;
  };
};
