export const errorCodes = [
  "INVALID_ACCESS_TOKEN",
  "RESOURCE_NOT_FOUND",
  "EMAIL_NOT_VERIFIED",
  "SHOP_NAME_TAKEN",
  "SHOP_NOT_VERIFIED",
  "SHOP_NOT_ACTIVE",
  "FORBIDDEN",
  "INVALID_LISTING_STATE",
  "INVALID_CATEGORY",
  "LISTING_CATEGORY_BANNED",
  "LISTING_DISCLOSURE_REQUIRED",
  "CATALOG_IMAGE_LIMIT",
  "SELLER_DOCUMENT_UPLOAD_FAILED",
  "LISTING_IMAGE_REQUIRED",
  "PII_COLUMN_FORBIDDEN",
  "SPREADSHEET_FORMAT_INVALID",
  "MANIFEST_PACKAGE_CONFLICT",
  "MANIFEST_IDEMPOTENCY_CONFLICT",
  "MANIFEST_PREVIEW_NOT_COMMITTABLE",
  "VALIDATION_FAILED",
  "INTERNAL_ERROR"
] as const;

export type ErrorCode = (typeof errorCodes)[number];

export type ErrorResponse = {
  error: {
    code: ErrorCode;
    message: string;
    requestId: string;
  };
};
