/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActorContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createShop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/{shopId}/listings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        get: operations["listShopListings"];
        put?: never;
        post: operations["createListingDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/{shopId}/listings/{listingId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/{shopId}/listings/{listingId}/images/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCatalogImageUploadIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/{shopId}/listings/{listingId}/images/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeCatalogImageUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/{shopId}/listings/{listingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateListingDraft"];
        trace?: never;
    };
    "/v1/listings/{listingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicListing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicListings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            status: "ok";
        };
        Category: {
            id: string;
            name: string;
        };
        ShopAccess: {
            shopId: string;
            displayName: string;
            /** @enum {string} */
            role: "OWNER" | "MANAGER" | "WAREHOUSE" | "ACCOUNTING";
            /** @enum {string} */
            kycStatus: "PENDING" | "VERIFIED" | "REJECTED";
            /** @enum {string} */
            shopStatus: "ONBOARDING" | "ACTIVE" | "PAUSED" | "LOCKED_INSUFFICIENT_FUND" | "SUSPENDED";
        };
        ActorContext: {
            /** Format: uuid */
            id: string;
            profileStatus: ("ACTIVE" | "SUSPENDED" | "DELETED") | null;
            shops: (components["schemas"]["ShopAccess"] & {
                id: string;
                membershipStatus: string;
                status: string;
            })[];
        };
        CreateListing: {
            title: string;
            description?: string;
            categoryId: string;
            /** @enum {string} */
            conditionGrade: "NEW_SEALED" | "LIKE_NEW_99" | "GOOD" | "FAIR" | "DEFECT";
            conditionNotes: string;
            price: number;
            weightGram: number;
        };
        UpdateListingDraft: components["schemas"]["CreateListing"];
        CreateCatalogImageUpload: {
            /** @enum {string} */
            mimeType: "image/jpeg" | "image/png" | "image/webp";
            sizeBytes: number;
        };
        CatalogImageUploadIntent: {
            key: string;
            /** Format: uri */
            uploadUrl: string;
            /** Format: date-time */
            expiresAt: string;
            headers: {
                [key: string]: string;
            };
        };
        ListingImage: {
            key: string;
            /** Format: uri */
            url: string;
            width: number;
            height: number;
        };
        Listing: components["schemas"]["CreateListing"] & {
            id: string;
            shopId: string;
            shopDisplayName: string;
            images: components["schemas"]["ListingImage"][];
            /** @enum {string} */
            status: "DRAFT" | "PENDING_REVIEW" | "ACTIVE" | "HIDDEN_BY_FUND" | "RESERVED" | "SOLD" | "RELISTABLE" | "SUSPENDED" | "DELISTED";
            publishedAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ListingPolicyResult: {
            /** @enum {string} */
            outcome: "ACTIVE" | "PENDING_REVIEW";
            policyLevel: ("BANNED" | "MANUAL_REVIEW" | "DISCLOSURE") | null;
            policyVersion: string | null;
            message: string;
        };
        PublishListingResult: {
            listing: components["schemas"]["Listing"];
            policy: components["schemas"]["ListingPolicyResult"];
        };
        PublicListing: {
            id: string;
            shopId: string;
            shopDisplayName: string;
            title: string;
            description?: string;
            categoryId: string;
            /** @enum {string} */
            conditionGrade: "NEW_SEALED" | "LIKE_NEW_99" | "GOOD" | "FAIR" | "DEFECT";
            conditionNotes: string;
            price: number;
            images: components["schemas"]["ListingImage"][];
            publishedAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        PublicListingPage: {
            items: components["schemas"]["PublicListing"][];
            nextCursor: string | null;
        };
    };
    responses: never;
    parameters: {
        ShopId: string;
        ListingId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database is reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getActorContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current actor and memberships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorContext"];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active categories available to the seller picker */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    createShop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    displayName: string;
                    /** @enum {string} */
                    legalType: "INDIVIDUAL" | "HOUSEHOLD" | "ENTERPRISE";
                };
            };
        };
        responses: {
            /** @description Shop created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopAccess"];
                };
            };
        };
    };
    listShopListings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shop listings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"][];
                };
            };
        };
    };
    createListingDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateListing"];
            };
        };
        responses: {
            /** @description Draft created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    publishListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: components["parameters"]["ShopId"];
                listingId: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy evaluated; listing activated or sent to manual review */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishListingResult"];
                };
            };
        };
    };
    createCatalogImageUploadIntent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: components["parameters"]["ShopId"];
                listingId: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCatalogImageUpload"];
            };
        };
        responses: {
            /** @description Signed catalog image upload intent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogImageUploadIntent"];
                };
            };
        };
    };
    completeCatalogImageUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: components["parameters"]["ShopId"];
                listingId: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    key: string;
                };
            };
        };
        responses: {
            /** @description Uploaded image metadata verified and attached to the draft */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    updateListingDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: components["parameters"]["ShopId"];
                listingId: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateListingDraft"];
            };
        };
        responses: {
            /** @description Draft updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    getPublicListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicListing"];
                };
            };
        };
    };
    listPublicListings: {
        parameters: {
            query?: {
                cursor?: string;
                q?: string;
                category?: string;
                shopId?: string;
                sort?: "newest" | "price_asc" | "price_desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public listings page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicListingPage"];
                };
            };
        };
    };
}
