/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActorContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seller-onboarding/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSellerDocumentUploadIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kyc/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startKyc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kyc/document/front": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitKycDocumentFront"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kyc/document/back": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitKycDocumentBack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kyc/selfie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitKycSelfie"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kyc/tax": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitKycTax"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kyc/bank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitKycBank"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kyc/{kycId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getKycStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/kyc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Requires database staff role MODERATOR or SUPER_ADMIN, ACTIVE profile/role, and verified JWT aal2. */
        get: operations["listKycReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/kyc/{kycId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Requires database staff role MODERATOR or SUPER_ADMIN, ACTIVE profile/role, and verified JWT aal2. */
        get: operations["getKycReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/kyc/{kycId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requires database staff role MODERATOR or SUPER_ADMIN, ACTIVE profile/role, and verified JWT aal2. */
        post: operations["decideKycReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createShop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/{shopId}/listings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        get: operations["listShopListings"];
        put?: never;
        post: operations["createListingDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/{shopId}/return-imports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewReturnManifest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/{shopId}/return-imports/{batchId}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["commitReturnManifest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/{shopId}/listings/{listingId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/{shopId}/listings/{listingId}/images/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCatalogImageUploadIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/{shopId}/listings/{listingId}/images/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeCatalogImageUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/shops/{shopId}/listings/{listingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateListingDraft"];
        trace?: never;
    };
    "/v1/listings/{listingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicListing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicListings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                code: string;
                message: string;
                requestId: string;
            };
        };
        Health: {
            /** @constant */
            status: "ok";
        };
        Category: {
            id: string;
            name: string;
        };
        ShopAccess: {
            shopId: string;
            displayName: string;
            /** @enum {string} */
            role: "OWNER" | "MANAGER" | "WAREHOUSE" | "ACCOUNTING";
            /** @enum {string} */
            kycStatus: "PENDING" | "PROCESSING" | "VERIFIED" | "REJECTED" | "MANUAL_REVIEW";
            /** @enum {string} */
            shopStatus: "ONBOARDING" | "ACTIVE" | "PAUSED" | "LOCKED_INSUFFICIENT_FUND" | "SUSPENDED";
        };
        ActorContext: {
            /** Format: uuid */
            id: string;
            profileStatus: ("ACTIVE" | "SUSPENDED" | "DELETED") | null;
            shops: {
                id: string;
                displayName: string;
                /** @enum {string} */
                role: "OWNER" | "MANAGER" | "WAREHOUSE" | "ACCOUNTING";
                membershipStatus: string;
                kycId: string | null;
                /** @enum {string} */
                kycStatus: "PENDING" | "PROCESSING" | "VERIFIED" | "REJECTED" | "MANUAL_REVIEW";
                /** @enum {string} */
                status: "ONBOARDING" | "ACTIVE" | "PAUSED" | "LOCKED_INSUFFICIENT_FUND" | "SUSPENDED";
            }[];
        };
        CreateListing: {
            title: string;
            description?: string;
            categoryId: string;
            /** @enum {string} */
            conditionGrade: "NEW_SEALED" | "LIKE_NEW_99" | "GOOD" | "FAIR" | "DEFECT";
            conditionNotes: string;
            price: number;
            weightGram: number;
        };
        UpdateListingDraft: components["schemas"]["CreateListing"];
        CreateCatalogImageUpload: {
            /** @enum {string} */
            mimeType: "image/jpeg" | "image/png" | "image/webp";
            sizeBytes: number;
        };
        CreateSellerDocumentUpload: {
            /** @enum {string} */
            kind: "AVATAR" | "CCCD_FRONT" | "CCCD_BACK" | "SELFIE";
            /** @enum {string} */
            mimeType: "image/jpeg" | "image/png" | "image/webp";
            sizeBytes: number;
        };
        CatalogImageUploadIntent: {
            key: string;
            /** Format: uri */
            uploadUrl: string;
            /** Format: date-time */
            expiresAt: string;
            headers: {
                [key: string]: string;
            };
        };
        KycStartResult: components["schemas"]["KycStatus"] & {
            id: string;
        };
        KycReview: {
            reason: string;
            /** Format: date-time */
            reviewedAt: string;
        };
        KycIdentity: {
            /** @description Masked identifier; only the last four digits are shown. */
            citizenId: string | null;
            fullName: string | null;
            dateOfBirth: string | null;
            gender: string | null;
            address: string | null;
            issuedAt: string | null;
        };
        KycVerification: {
            documentValid: boolean | null;
            faceMatched: boolean | null;
            faceScore: number | null;
            livenessPassed: boolean | null;
            livenessScore: number | null;
        };
        AdminKycQueueItem: {
            kycId: string;
            shopId: string;
            shopDisplayName: string;
            /** @constant */
            status: "MANUAL_REVIEW";
            provider: string;
            /** Format: date-time */
            submittedAt: string;
        };
        AdminKycQueue: {
            items: components["schemas"]["AdminKycQueueItem"][];
            nextCursor: string | null;
        };
        KycDecision: {
            /** @enum {string} */
            decision: "APPROVE" | "REJECT";
            /** @description Trimmed non-empty reason visible to seller. */
            reason: string;
        };
        KycDecisionResult: {
            kycId: string;
            /** @enum {string} */
            kycStatus: "VERIFIED" | "REJECTED";
            review: components["schemas"]["KycReview"];
        };
        AdminKycDetail: {
            kycId: string;
            shopId: string;
            shopDisplayName: string;
            /** @enum {string} */
            status: "PENDING" | "PROCESSING" | "VERIFIED" | "REJECTED" | "MANUAL_REVIEW";
            provider: string;
            /** Format: date-time */
            submittedAt: string;
            identity: components["schemas"]["KycIdentity"];
            verification: components["schemas"]["KycVerification"];
            review: components["schemas"]["KycReview"] | null;
            tax: {
                status: ("VERIFIED" | "NOT_FOUND" | "UNAVAILABLE") | null;
                registeredName: string | null;
            };
            bank: {
                bankCode: string | null;
                /** @description Masked account number. */
                accountNumber: string | null;
                status: ("VERIFIED" | "NOT_FOUND" | "UNAVAILABLE") | null;
                registeredName: string | null;
                nameMatchScore: number | null;
            };
        };
        KycStatus: {
            success: boolean;
            /** @enum {string} */
            kycStatus: "PENDING" | "PROCESSING" | "VERIFIED" | "REJECTED" | "MANUAL_REVIEW";
            review: components["schemas"]["KycReview"] | null;
            identity: components["schemas"]["KycIdentity"];
            verification: components["schemas"]["KycVerification"];
        };
        ListingImage: {
            key: string;
            /** Format: uri */
            url: string;
            width: number;
            height: number;
        };
        Listing: components["schemas"]["CreateListing"] & {
            id: string;
            shopId: string;
            shopDisplayName: string;
            images: components["schemas"]["ListingImage"][];
            /** @enum {string} */
            status: "DRAFT" | "PENDING_REVIEW" | "ACTIVE" | "HIDDEN_BY_FUND" | "RESERVED" | "SOLD" | "RELISTABLE" | "SUSPENDED" | "DELISTED";
            publishedAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ListingPolicyResult: {
            /** @enum {string} */
            outcome: "ACTIVE" | "PENDING_REVIEW";
            policyLevel: ("BANNED" | "MANUAL_REVIEW" | "DISCLOSURE") | null;
            policyVersion: string | null;
            message: string;
        };
        PublishListingResult: {
            listing: components["schemas"]["Listing"];
            policy: components["schemas"]["ListingPolicyResult"];
        };
        ReturnManifestLineDraft: {
            sourceItemRef: string;
            sourceSku?: string;
            sourceQuantity: number;
            productName: string;
            variantName?: string;
            brand?: string;
            sourceCategory?: string;
            originalUnitPriceVnd?: number;
            returnReason?: string;
            productImageUrls: string[];
            reboxCategoryId: string;
        };
        ReturnManifestDraft: {
            /** @enum {string} */
            source: "SPREADSHEET" | "PLATFORM_API";
            /** @enum {string} */
            sourcePlatform: "SHOPEE" | "TIKTOK";
            sourceTrackingNo: string;
            sourceOrderRef?: string;
            sourceReturnRef?: string;
            /** Format: date-time */
            returnedAt?: string;
            packageWeightGram?: number;
            packageDimensionsCm?: {
                length: number;
                width: number;
                height: number;
            };
            packageListingPriceVnd: number;
            lines: components["schemas"]["ReturnManifestLineDraft"][];
        };
        /** @enum {string} */
        ReturnManifestIssueCode: "INVALID_FIELD" | "INVALID_CATEGORY" | "PACKAGE_FIELD_CONFLICT" | "DUPLICATE_SOURCE_ITEM_REF";
        ReturnManifestPreviewRow: {
            rowIndex: number;
            packageGroup: string;
            warningCodes: components["schemas"]["ReturnManifestIssueCode"][];
            errorCodes: components["schemas"]["ReturnManifestIssueCode"][];
        };
        ReturnManifestPreview: {
            batchId: string;
            rows: components["schemas"]["ReturnManifestPreviewRow"][];
            drafts: components["schemas"]["ReturnManifestDraft"][];
            canCommit: boolean;
        };
        CommitReturnManifestResult: {
            batchId: string;
            packageIds: string[];
            lineCount: number;
        };
        PublicListing: {
            id: string;
            shopId: string;
            shopDisplayName: string;
            title: string;
            description?: string;
            categoryId: string;
            /** @enum {string} */
            conditionGrade: "NEW_SEALED" | "LIKE_NEW_99" | "GOOD" | "FAIR" | "DEFECT";
            conditionNotes: string;
            price: number;
            images: components["schemas"]["ListingImage"][];
            publishedAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        PublicListingPage: {
            items: components["schemas"]["PublicListing"][];
            nextCursor: string | null;
        };
    };
    responses: never;
    parameters: {
        ShopId: string;
        ListingId: string;
        BatchId: string;
    };
    requestBodies: {
        KycImage: {
            content: {
                "application/json": {
                    kycId: string;
                    objectKey: string;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database is reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getActorContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current actor and memberships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorContext"];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active categories available to the seller picker */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    createSellerDocumentUploadIntent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSellerDocumentUpload"];
            };
        };
        responses: {
            /** @description Signed upload intent for an avatar or private KYC document */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogImageUploadIntent"];
                };
            };
        };
    };
    startKyc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    shopId: string;
                };
            };
        };
        responses: {
            /** @description Idempotently starts KYC for an owned shop */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycStartResult"];
                };
            };
        };
    };
    submitKycDocumentFront: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["KycImage"];
        responses: {
            /** @description Normalized front-side OCR and document validation result */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycStatus"];
                };
            };
        };
    };
    submitKycDocumentBack: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["KycImage"];
        responses: {
            /** @description Normalized back-side OCR and document validation result */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycStatus"];
                };
            };
        };
    };
    submitKycSelfie: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["KycImage"];
        responses: {
            /** @description Normalized face-match and liveness result */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycStatus"];
                };
            };
        };
    };
    submitKycTax: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    kycId: string;
                    taxCode: string;
                };
            };
        };
        responses: {
            /** @description Tax verification recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycStatus"];
                };
            };
        };
    };
    submitKycBank: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    kycId: string;
                    bankCode: string;
                    accountNumber: string;
                };
            };
        };
        responses: {
            /** @description Bank account verified and authoritative holder name compared */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycStatus"];
                };
            };
        };
    };
    getKycStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kycId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current normalized KYC status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycStatus"];
                };
            };
        };
    };
    listKycReviews: {
        parameters: {
            query?: {
                status?: "MANUAL_REVIEW";
                /** @description Opaque nextCursor from the previous page. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized KYC review response */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminKycQueue"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Active moderator/super admin and AAL2 required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description KYC not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Invalid query, body or key */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getKycReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kycId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized KYC review response */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminKycDetail"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Active moderator/super admin and AAL2 required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description KYC not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Invalid query, body or key */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    decideKycReview: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                kycId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KycDecision"];
            };
        };
        responses: {
            /** @description Authorized KYC review response */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KycDecisionResult"];
                };
            };
            /** @description Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Active moderator/super admin and AAL2 required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description KYC not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Already decided or idempotency key reused with a different payload */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Invalid query, body or key */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createShop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    displayName: string;
                    /** @enum {string} */
                    legalType: "INDIVIDUAL" | "HOUSEHOLD" | "ENTERPRISE";
                    description: string;
                    phone: string;
                    pickupAddress: {
                        contactName: string;
                        addressLine: string;
                        province: string;
                        district: string;
                        ward: string;
                    };
                    kyc: {
                        taxCode: string;
                        bankCode: string;
                        bankAccount: string;
                        accountHolder: string;
                    };
                    documents: {
                        avatarKey: string;
                        cccdFrontKey: string;
                        cccdBackKey: string;
                    };
                    carrierCodes: ("GHN" | "GHTK")[];
                };
            };
        };
        responses: {
            /** @description Shop created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopAccess"];
                };
            };
        };
    };
    listShopListings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shop listings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"][];
                };
            };
        };
    };
    createListingDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateListing"];
            };
        };
        responses: {
            /** @description Draft created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    previewReturnManifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: components["parameters"]["ShopId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Parsed and allowlisted return manifest preview */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReturnManifestPreview"];
                };
            };
        };
    };
    commitReturnManifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: components["parameters"]["ShopId"];
                batchId: components["parameters"]["BatchId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    idempotencyKey: string;
                };
            };
        };
        responses: {
            /** @description Idempotently committed return packages and source lines */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitReturnManifestResult"];
                };
            };
        };
    };
    publishListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: components["parameters"]["ShopId"];
                listingId: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy evaluated; listing activated or sent to manual review */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishListingResult"];
                };
            };
        };
    };
    createCatalogImageUploadIntent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: components["parameters"]["ShopId"];
                listingId: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCatalogImageUpload"];
            };
        };
        responses: {
            /** @description Signed catalog image upload intent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogImageUploadIntent"];
                };
            };
        };
    };
    completeCatalogImageUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: components["parameters"]["ShopId"];
                listingId: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    key: string;
                };
            };
        };
        responses: {
            /** @description Uploaded image metadata verified and attached to the draft */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    updateListingDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shopId: components["parameters"]["ShopId"];
                listingId: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateListingDraft"];
            };
        };
        responses: {
            /** @description Draft updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    getPublicListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicListing"];
                };
            };
        };
    };
    listPublicListings: {
        parameters: {
            query?: {
                cursor?: string;
                q?: string;
                category?: string;
                shopId?: string;
                sort?: "newest" | "price_asc" | "price_desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public listings page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicListingPage"];
                };
            };
        };
    };
}
